project:
  name: "Functions"
  description: "A library of independent functions"
  requirements:
  - name: "Add function"
    description: Implement the 'add' function which will take two integers and
      return their sum.
  - name: "Subtract function"
    description: Implement the 'subtract' function which will take two integers and
      return their difference.
